package de.krautundrueben.krautundrueben.controller;


import de.krautundrueben.krautundrueben.models.Order;
import de.krautundrueben.krautundrueben.repository.OrderRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/orders") // This means URL's start with /demo (after Application path)
public class OrderController {
    @Autowired(required = false) // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private OrderRepository orderRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewUser (@RequestParam String kundenNr , @RequestParam String bestellDatum, @RequestParam String rechnungsBetrag) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Order n = new Order((int) orderRepository.count() + 1 , kundenNr, bestellDatum, rechnungsBetrag);
        orderRepository.save(n);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Order> getAllUsers() {
        // This returns a JSON or XML with the users
        return orderRepository.findAll();
    }
}